### PR TITLE
support common_prefixes response object parsing.

### LINKED ISSUE #30: should handle CommonPrefixes in ListObjectsV2
i've monkey patched this into my code for now, but would like to get something upstream.

if this approach is ok, would be happy to submit a PR with the change and the docs updates.  This is API breaking, not sure how you want to deal with that.

https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_ResponseSyntax

if it's not clear the usecase, here's a simple example: if you have objects in s3, like "ab/my/doc.txt", "ab/foo/doc.txt" and do a query like prefix="ab/", delimeter="/", you will get commonprefix of "ab/my/", "ab/foo/", and zero payload in contents part of the response..    

this is the significant parts of the patch:

```python
def parse_list_objects(
    payload: bytes,
) -> Tuple[
    List[AwsObjectMeta],
    List[str],
]:
    ...
    prefixes = [el.text for el in root.findall(f'{{{NS}}}CommonPrefixes/{{{NS}}}Prefix')]
    ...
    return result, prefixes, continuation_token


async def list_objects_v2_patch(
    self,
    object_name: t.Union[str, Path] = '/',
    *,
    bucket: t.Optional[str] = None,
    prefix: t.Optional[t.Union[str, Path]] = None,
    delimiter: t.Optional[str] = None,
    max_keys: t.Optional[int] = None,
    start_after: t.Optional[str] = None,
) -> t.AsyncIterator[t.Tuple[t.List[AwsObjectMeta], t.List[str]]]:

       ...
            metadata, common_prefix, continuation_token = parse_list_objects(payload)
            if not metadata and not common_prefix:
                break
            yield metadata, common_prefix
        ...
```

### PR DESCRIPTION
**Pull request by toppk**
resolves #30

### CODE REVIEW

**Review by mosquito — APPROVED** [review]

**Comment by toppk** [comment]
i figured out how to run tests (there should be developer docs):
```shell
podman run -p 9090:9090 --env initialBuckets=test   docker://adobe/s3mock
S3_URL=http://user:hackme@localhost:9090/test/ poetry run pytest -vv tests
```

but there is an issue:
if you run:
```shell
$ curl 'http://user:hackme@localhost:9090/test/?list-type=2&prefix=test/&delimiter=/&encoding-type=url'
<ListBucketResult><Name>test</Name><Prefix>test/</Prefix><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><KeyCount>0</KeyCount><EncodingType>url</EncodingType></ListBucketResult>You have new mail in /var/spool/mail/toppk
```

you see there isn't the xml header with the namespace.

the list objects tests are false negative because there is no response.  if you added a bogus `assert 1==2` test inside the with block you will see that.

a fix is to set the NS = "" (in parse_list_objects, if you do it a the module level in xml.py, it will break other things).

obviously this is an issue in my s3mock, but given there's a potential for false negative in the way the tests are structured, it may be an issue on your side as well.  I've tried to look at s3mock to see if I can figure out what's happening there but nothing so far.

**Comment by toppk** [comment]
i've tested a bunch of older version of s3mock, and same issues.

for references this is what aws s3 gives, which is why this code works in prod (for me).
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
...
</ListBucketResult>
```

**Comment by mosquito** [comment]
@toppk may be s3mock doesn’t support that features? Could you please test it again with minio?

**Comment by toppk** [comment]
minio behaves properly. 


```shell
$ curl http://MY-MINIO-SERVER/test
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>
```

I'm not sure if there's some sort of enviriomental/pebcak issue, but I've created an issue on s3mock to see if they can help me out.

https://github.com/adobe/S3Mock/issues/1754

**Review by mosquito — APPROVED** [review]

**Review by dizballanze — APPROVED** [review]

**Pull request merged**
