### PR TITLE
Support session token

### PR DESCRIPTION
**Pull request by toppk**
This allows users to use ec2 instance roles.   A more detailed implementation would query the metadata services directly to fill in the information directly.  Regardless, this is the bare minimum implementation.  Requires an updated aws-request-signer, which was released four months ago.

### CODE REVIEW

**Comment by toppk** [comment]
i didn't update the poetry.lock file, so the tests fail.  not sure if you'd want my poetry.lock anyway, as it looks quite different after running an update.

**Comment by mosquito** [comment]
@toppk nice changes, will be better then you add some sentences to the README about it.

**Comment by mosquito** [comment]
> i didn't update the poetry.lock file, so the tests fail. not sure if you'd want my poetry.lock anyway, as it looks quite different after running an update.

Just run `poetry update aws-request-signer` this should change the minimum packages. BTW, for me it’s not a problem to update the lockfile completely.

**Comment by toppk** [comment]
okay, I thought it would be confusing to add token to the Usage section, so I documented it down below.

I updated the lock file, and it seems like category is going away from poetry.lock as documented here:
https://github.com/python-poetry/poetry/issues/5702

**Comment by mosquito** [comment]
released in version `0.8.7`

**Pull request merged**
